### ISSUE TITLE
Digital sources (suggestions)

### ISSUE THREAD

**Issue by mrchristian** [NFDI4Culture/cp4c#8]
## Suggested objects, queries, computes

- Image
- 3D model
- Video
- Query

--

- Image: Siege III: The Fortress of Raab occupied by the Turks, 1594. Painting, https://wikibase.wbworkshop.tibwiki.io/wiki/Item:Q505

- Model with annotation - https://wikibase.wbworkshop.tibwiki.io/wiki/Item:Q469

- Video - Developing an open source data pipeline for participation in community knowledge bases - https://av.tib.eu/media/56162

- Query we could emulate and [make interactive all painting]( https://query.wbworkshop.tibwiki.io/embed.html#SELECT%20%3Fitem%20%3FitemLabel%20%3FcreationDateStart%20%3FcreationDateEnd%20%3Finscription%20%3FmaterialLabel%20%3FmethodLabel%20%3Fdescription%20%3Fmedia%0AWHERE%20%7B%20%0A%20%20%20%20%3Fitem%20tibt%3AP25%20tib%3AQ60.%0A%20%20%20%20%3Fitem%20tibt%3AP79%20%3FcreationDateStart.%0A%20%20%20%20%3Fitem%20tibt%3AP80%20%3FcreationDateEnd.%0A%20%20%20%20%3Fitem%20tibt%3AP18%20%3Finscription.%0A%20%20%20%20%3Fitem%20tibt%3AP38%20%3Fmaterial.%0A%20%20%20%20%3Fitem%20tibt%3AP39%20%3Fmethod.%0A%20%20%20%20%3Fitem%20tibt%3AP26%20%3Fdescription.%0A%20%20%20%20%3Fitem%20tibt%3AP16%20%3Fmedia%0A%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%20%0A%0A%23All%20paintings%20from%20%22Belagerungsszenen%20des%20Langen%20T%C3%BCrkenkriegs%22)

**Comment by mrchristian** [comment]
Link to issue #1

**Comment by mrchristian** [comment]
Relies on services:

- [https://wikibase.wbworkshop.tibwiki.io/](https://wikibase.wbworkshop.tibwiki.io/)
- [https://av.tib.eu/](https://av.tib.eu/)
- https://deckenmalerei-bilder.badw.de/ - images (paintings)
- https://cloud.nfdi4culture.de/ - 3D model and images media

**Comment by SimonXIX** [comment]
Great, thanks. 

**Image:** I've updated the code already written in linked_open_data.ipynb to pull the image for Q505 as suggested. That works well if you run the Notebook in Jupyter Labs and then render in Quarto to produce the static page. 

**Query:** One issue I was having with running SPARQL queries against https://query.wbworkshop.tibwiki.io is that I couldn't find the SPARQL endpoint URL. At Wikidata, this is https://query.wikidata.org/bigdata/namespace/wdq/sparql, for example, but I couldn't find the equivalent for the NFDI4Culture Wikibase instance. For now, I've got Python code in the Notebook to pull from Wikidata as a test.

I'll have a look at the others hopefully this week.

**Comment by mrchristian** [comment]
Hey good one. Yep I was onbly suggesting above as options, and realised you'd already be on it. I'll ask about the endpoint for you.

Fee free to render the Quarto book and push onto GitHub pages - or I can have a go tomorrow AM.

**Comment by luguenth** [comment]
Hey there, the SPARQL endpoint for wbworkshop should be: 

https://query.wbworkshop.tibwiki.io/proxy/wdqs/bigdata/namespace/wdq/sparql

**Comment by SimonXIX** [comment]
> Hey good one. Yep I was onbly suggesting above as options, and realised you'd already be on it. I'll ask about the endpoint for you.
> 
> Fee free to render the Quarto book and push onto GitHub pages - or I can have a go tomorrow AM.

Hi Simon. I ran the Jupyter Notebook, rendered the output in Quarto, and pushed to GitHub Pages. I wasn't able to push from home due to the large file size of the image but I'm on campus today and used their more robust bandwidth to push successfully.

**Comment by mrchristian** [comment]
I think your looking for endpoint here https://query.wbworkshop.tibwiki.io/

**Comment by mrchristian** [comment]
I'll have play tomorrow, Quart allows multi-format output, as well as display code, hide code, dropdown code display options - on rendering. FYI I change repo name and the Quarto settings need updating. I'll check in tomorrow morning.
